fail_fast: false

repos:
  # Validation first
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/crate-ci/typos
    rev: v1.42.1
    hooks:
      - id: typos

  # uv lock check
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.0
    hooks:
      - id: uv-lock
        args: [--check]
        additional_dependencies: [keyrings.google-artifactregistry-auth]

  # Generic checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements
      - id: check-json
      - id: check-yaml
      - id: name-tests-test
        args: [--pytest-test-first]
        exclude: ^(tests/data|tests/fixtures|tests/.*\/(data|fixtures))\/.*\.py$
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-use-type-annotations

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
