return function(ctx)
  local M = {}

  local function copyTable(t)
    if type(t) ~= "table" then return nil end
    local out = {}
    for k, v in pairs(t) do out[k] = v end
    return out
  end

  local function hasKeys(t)
    return type(t) == "table" and next(t) ~= nil
  end

  local function shellQuote(s)
    return "'" .. tostring(s):gsub("'", "'\\''") .. "'"
  end

  local function chmod(mode, path)
    hs.execute("/bin/chmod " .. mode .. " " .. shellQuote(path))
  end

  -- Write clipboard data for our copy/paste round-trip, tagged so well-behaved clipboard managers
  -- (the nspasteboard.org convention) do not record it in history.
  function M.writeDataQuiet(data)
    local tagged = copyTable(data)
    if not tagged then return false end
    tagged["org.nspasteboard.TransientType"] = ""
    tagged["org.nspasteboard.AutoGeneratedType"] = ""
    local ok, wrote = pcall(hs.pasteboard.writeAllData, tagged)
    return ok and wrote
  end

  function M.setTextQuiet(text)
    if M.writeDataQuiet({ ["public.utf8-plain-text"] = text }) then return end
    hs.pasteboard.setContents(text)
  end

  function M.snapshot()
    local snap = { text = hs.pasteboard.getContents() }
    local ok, data = pcall(hs.pasteboard.readAllData)
    if ok and hasKeys(data) then snap.data = copyTable(data) end
    return snap
  end

  function M.restore(snap)
    if type(snap) ~= "table" then return end
    if hasKeys(snap.data) and M.writeDataQuiet(snap.data) then return end
    if snap.text ~= nil then
      M.setTextQuiet(snap.text)
    else
      M.setTextQuiet("")
    end
  end

  function M.ensurePrivateTmpDir()
    hs.fs.mkdir(ctx.HOME .. "/.local")
    hs.fs.mkdir(ctx.HOME .. "/.local/share")
    hs.fs.mkdir(ctx.DATA_DIR)
    hs.fs.mkdir(ctx.TMP_DIR)
    chmod("700", ctx.DATA_DIR)
    chmod("700", ctx.TMP_DIR)
  end

  function M.chmod(mode, path)
    chmod(mode, path)
  end

  return M
end
